language: node_js
    - "8"
install:
    - npm cache rm --force
    - npm install
services:
    - postgresql
# cache:
#     directories:
#         - "node_modules"
script: npm run test
before_script:
    - npm install mocha chai chai-http faker cross-env
    - cd server
    - npm run create:test:db
    - npm run migrate:test
    - npm run seed:test
after_script:
